#!/bin/env bash

CYAN=`tput setaf 6`
BOLD=`tput bold`
NONE=`tput sgr0`

# spinner based on https://stackoverflow.com/a/20369590
spinner() {
    local pid=$!
    local delay=0.25
    local spinstr='|/-\'
	local sufix=$1

    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf "${CYAN}Cloning $sufix... ${NONE} [%c]" "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\r"
    done

    printf "${CYAN}\rCloned $sufix           \n${NONE}"
}

function install() {
	local url=$1
	local tag=$2
	local dir=$3

	mkdir repo-temp
	git clone --quiet "$url" ./repo-temp 2>/dev/null 1>/dev/null &
	spinner "'${url}:${tag}' into '$dir'"

	cd ./repo-temp
	git checkout --quiet "$tag"
	cd ..

	if [[ -e "./$dir/" ]]; then
		rm -rf "./$dir/"
	fi

	rm -rf ./repo-temp/.git
	mv "./repo-temp/" "./$dir/"
	rm -rf "./repo-temp/"
}

install https://github.com/g-truc/glm 0.9.9.8 glm
install https://github.com/google/shaderc v2023.4 shaderc
install https://github.com/glfw/glfw 3fa2360720eeba1964df3c0ecf4b5df8648a8e52 glfw
install https://github.com/nothings/stb 5736b15f7ea0ffb08dd38af21067c314d6a3aae9 stb

echo -e "\n${BOLD}Running install scripts...${NONE}"

# shaderc
cd shaderc
./utils/git-sync-deps
